version: '3.8'

services:
  app:
    build: .
    container_name: php_app
    ports:
      - "8080:80"  # porta padrão para o Railway
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
